# Generated by Django 6.0 on 2026-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad_core', '0002_emailverification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'type', 'text'), name='unique_exam_question_text'),
        ),
    ]
